repos:
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
  - id: bandit
    args: [-r, -c, .bandit.yml]
    language_version: python3.8
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    language_version: python3.8
- repo: https://github.com/psf/black.git
  rev: 23.1.0
  hooks:
  - id: black
    language_version: python3.8
- repo: https://github.com/pycqa/isort
  rev: 5.11.5
  hooks:
  - id: isort
    language_version: python3.8
