repos:
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.7
  hooks:
  - id: bandit
    args: [-r, -c, .bandit.yml]
    language_version: python3.8
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    language_version: python3.8
- repo: https://github.com/psf/black.git
  rev: 24.1.1
  hooks:
  - id: black
    language_version: python3.8
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    language_version: python3.8
